dist: xenial
language: python
#addons:
#  apt:
#    packages:
      #- python3-dbus
      #- python3-gi
      #- libdbus-1-dev

python:
  - '3.6'
#  - '3.7'
#  - '3.8'
install:
  - pip install -r requirements_dev.txt
  - pip install -e .
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then travis_retry pip install dbus-python; fi
#  - pip install -r requirements.txt
script:
  - pytest --cov=warg --ignore=tests/test_toaster.py
  - coveralls
  - black --check warg

