dist: xenial
language: python
addons:
  apt:
    packages:
       - wkhtmltopdf

python:
  - '3.6'
#  - '3.7'
#  - '3.8'
install:
  - pip install -r requirements_dev.txt
  - pip install -e .
script:
  - pytest --cov=munin
  - coveralls
  - black --check munin

